FROM python:3.11-slim

WORKDIR /app
COPY web_platform/flask/webhooks/requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r /app/requirements.txt

COPY web_platform /app/web_platform
EXPOSE 5001
CMD ["python", "web_platform/flask/webhooks/app.py"]



