FROM python:3.11-slim

WORKDIR /app
COPY web_platform/django/saas_app/requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r /app/requirements.txt

COPY web_platform/django/saas_app /app/saas_app
WORKDIR /app/saas_app
EXPOSE 8001
CMD ["python", "manage.py", "runserver", "0.0.0.0:8001"]



